### ISSUE TITLE
<Component> Embedded Video Player

### ISSUE THREAD

**Issue by PitaFLAME** [ASU-CodeDevils/CD-Academy#1]
For this task, you will need to create a fundamental component of our content system: The Video Player.

Please accomplish the following:
- Create a new component within /src/app/components/ named YoutubeEmbed.tsx, exporting a <YoutubeEmbed /> component.
- Component should have the following parameters:
    - src: (str)
    - width?: (number)
    - height?: (height)
    - className?: (str)

_60 points_

**Comment by jacobkobr** [comment]
I've started to work on this.

**Comment by PitaFLAME** [comment]
_Completed_
