### ISSUE TITLE
Fix dimmer dead zone

### ISSUE THREAD

**Issue by PitaFLAME** [ASU-CodeDevils/CD-Academy#4]
There's a dead zone for the dimmer on the right side of the screen when the login overlay is triggered.  Isolate the issue and resolve it, please.

Please accomplish the following:
- Make the dimmer span the entire screen
- When the Login Overlay is triggered, there is a small bar on the right side of the screen that is not covered by the dimmer.  It's hard to see because the Overlay immediately covers it, so you have to be fast (or spam the button) in order to see it.  You can remove the Overlay Window in order to get a better look at the issue.

_20 points_

**Comment by jacobkobr** [comment]
Hey can I work on this?

**Comment by PitaFLAME** [comment]
_Completed_
