### ISSUE TITLE
Fix Discord Badge Server Icon

### ISSUE THREAD

**Issue by PitaFLAME** [ASU-CodeDevils/CD-Academy#6]
The Discord icon for the CodeDevils server has been updated since this Discord badge was created.  The Discord badge's icon is out of date.  Please update the asset to the correct one.

Please accomplish the following:
- Swap the asset for the Discord server icon to the new one.  If you need the file, please reach out to @PitaFLAME 
- Ensure that the styling and size is consistent with the way the previous one was.

_10 points_

**Comment by adrianbparra** [comment]
Can I update this?

**Comment by PitaFLAME** [comment]
_Completed_
